services:
  database:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - qpnetwork
  grocery:
    build:
      context: .
      dockerfile: Dockerfile
    image: grocery-store
    restart: always
    ports:
      - 3000:3000
    depends_on:
      database:
        condition: service_healthy
    networks:
      - qpnetwork
volumes:
  pgdata:
networks:
  qpnetwork:
